using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Ali.Delivery.Generators;

[Generator]
public class DictionaryEntityEnumMappingSourceGenerator : IIncrementalGenerator
{
    private const string AttributeName = "MapDictionaryEntityAttribute";

    private const string AttributeSourceCode = $$"""
                                                 // <auto-generated/>

                                                 namespace {{Namespace}}
                                                 {
                                                     /// <summary>
                                                     /// Представляет атрибут для маппинга словарных сущностей.
                                                     /// </summary>
                                                     [System.AttributeUsage(System.AttributeTargets.Enum)]
                                                     public class {{AttributeName}} : System.Attribute
                                                     {
                                                         /// <summary>
                                                         /// Инициализирует новый экземпляр типа <see cref="MapDictionaryEntityAttribute" />.
                                                         /// </summary>
                                                         public {{AttributeName}}(System.Type dictionaryType){}
                                                     }
                                                 }
                                                 """;

    private const string ExtensionsNamespace = "Ali.Delivery.Order.Application.Extensions";
    private const string Namespace = "Ali.Delivery.Order.Generators";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource($"{AttributeName}.g.cs", SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        var provider = context.SyntaxProvider.CreateSyntaxProvider((s, _) => s is EnumDeclarationSyntax, GetClassDeclarationForSourceGen)
                              .Where(t => t.reportAttributeFound)
                              .Select((t, _) => t.Item1);

        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()), (ctx, t) => GenerateCode(ctx, t.Left, t.Right));
    }

    private static void GenerateCode(SourceProductionContext context, Compilation compilation, ImmutableArray<ClassInfo> classInfos)
    {
        foreach (var (enumDeclarationSyntax, dictClassInfo) in classInfos)
        {
            var semanticModel = compilation.GetSemanticModel(enumDeclarationSyntax.SyntaxTree);

            if (semanticModel.GetDeclaredSymbol(enumDeclarationSyntax) is not INamedTypeSymbol enumSymbol)
            {
                continue;
            }

            var namespaceName = enumSymbol.ContainingNamespace.ToDisplayString();
            var enumName = enumDeclarationSyntax.Identifier.Text;
            var enumFullName = $"{namespaceName}.{enumName}";
            var dictClassName = dictClassInfo.Name;
            var dictNamespace = dictClassInfo.ContainingNamespace.ToDisplayString();
            var dictClassFullName = $"{dictNamespace}.{dictClassName}";

            var fields = dictClassInfo.GetMembers()
                                      .OfType<IFieldSymbol>()
                                      .Where(m => m is { DeclaredAccessibility: Accessibility.Public, IsStatic: true, IsReadOnly: true } &&
                                                  m.ContainingType.Equals(m.Type, SymbolEqualityComparer.Default))
                                      .Select(m => m.Name);

            var enumValues = enumDeclarationSyntax.Members.Select(m => m.Identifier.Text);

            var list = enumValues.Intersect(fields)
                                 .ToList();

            var toDictLines = list.Select(n => $"{enumName}.{n} => {dictClassName}.{n},");

            var toEnumLines = list.Select(n => $"{{}} when value == {dictClassName}.{n} => {enumName}.{n},");

            var code = $$"""
                         // <auto-generated/>

                         #nullable enable

                         using System;
                         using System.Collections.Generic;
                         using {{enumName}} = {{enumFullName}};
                         using {{dictClassName}} = {{dictClassFullName}};

                         namespace {{ExtensionsNamespace}};

                         /// <summary>
                         /// Содержит набор методов расширения для преобразования типов.
                         /// </summary>
                         public static class {{enumName}}EnumExtensions
                         {
                         
                             /// <summary>
                             /// Преобразует значение <see cref="{{enumName}}"/> в значение <see cref="{{dictClassName}}"/>.
                             /// </summary>
                             /// <param name="code">Значение.</param>
                             /// <exception cref="ArgumentOutOfRangeException">
                             /// Возникает, если значение не поддерживается.
                             /// </exception>
                             public static {{dictClassName}} To{{dictClassName}}(this {{enumName}} code) =>
                                code switch
                                {
                                    {{string.Join("\n           ", toDictLines)}}
                                    _ => throw new ArgumentOutOfRangeException(nameof(code), code, "Неподдерживаемое значение типа {{enumName}}.")
                                };
                             
                             /// <summary>
                             /// Преобразует значение <see cref="{{dictClassName}}"/> в значение <see cref="{{enumName}}"/>.
                             /// </summary>
                             /// <param name="value">Значение.</param>
                             /// <exception cref="ArgumentOutOfRangeException">
                             /// Возникает, если значение не поддерживается.
                             /// </exception>
                             public static {{enumName}} To{{enumName}}(this {{dictClassName}} value) =>
                                 value switch
                                 {
                                     {{string.Join("\n            ", toEnumLines)}}
                                     _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Неподдерживаемое значение типа {{dictClassName}}.")
                                 };
                         }

                         """;

            context.AddSource($"{enumName}EnumExtensions.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }

    private static INamedTypeSymbol? GetAttrName(SemanticModel semanticModel, AttributeSyntax attributeSyntax, CancellationToken cancellationToken)
    {
        if (semanticModel.GetSymbolInfo(attributeSyntax, cancellationToken)
                         .Symbol is not IMethodSymbol attributeSymbol)
        {
            return null;
        }

        var attributeName = attributeSymbol.ContainingType.ToDisplayString();

        if (attributeName != $"{Namespace}.{AttributeName}")
        {
            return null;
        }

        var expressionSyntax = attributeSyntax.ArgumentList?.Arguments.FirstOrDefault()
                                              ?.Expression;

        if (expressionSyntax is TypeOfExpressionSyntax typeOfExpression)
        {
            return semanticModel.GetTypeInfo(typeOfExpression.Type, cancellationToken)
                                .Type as INamedTypeSymbol;
        }

        return null;
    }

    private static INamedTypeSymbol? GetAttrValue(SemanticModel semanticModel, MemberDeclarationSyntax classDeclarationSyntax, CancellationToken cancellationToken) =>
        (from attributeListSyntax in classDeclarationSyntax.AttributeLists
         from attributeSyntax in attributeListSyntax.Attributes
         select GetAttrName(semanticModel, attributeSyntax, cancellationToken)).FirstOrDefault();

    private static (ClassInfo, bool reportAttributeFound) GetClassDeclarationForSourceGen(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var classDeclarationSyntax = (EnumDeclarationSyntax)context.Node;

        var semanticModel = context.SemanticModel;

        var value = GetAttrValue(semanticModel, classDeclarationSyntax, cancellationToken);

        return value != null ? (new ClassInfo(classDeclarationSyntax, value), true) : (default, false);
    }

    private record struct ClassInfo(EnumDeclarationSyntax Class, INamedTypeSymbol DictTypeInfo);
}
