<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Ali.Delivery.Location.Application\Ali.Delivery.Location.Application.csproj"/>
        <ProjectReference Include="..\Ali.Delivery.Location.Domain\Ali.Delivery.Location.Domain.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions" Version="9.0.0"/>
        <PackageReference Include="LazyCache.AspNetCore" Version="2.4.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.6"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.6"/>
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.6"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.6"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.6"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4"/>
        <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
        <PackageReference Include="Refit" Version="8.0.0"/>
        <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0"/>
        <PackageReference Include="Telegram.Bot" Version="22.5.2-dev.6"/>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Migrations\"/>
    </ItemGroup>
</Project>
