<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableUnusedReferencesDetection>true</EnableUnusedReferencesDetection>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Ali.Delivery.Domain.Core" Version="1.0.1"/>
    </ItemGroup>
</Project>
